config/routes.rb
Rails.application.routes.draw do
  get 'shopping_list/show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'foods#index'

  resources :foods, except: [:update]
  resources :recipes, except: [:update] do
    resources :recipe_foods
  end

  get 'public_recipes', to: 'recipes#public'
  get 'general_shopping_list/:recipe_id', to: 'shoplist#show', as: 'general_shopping_list'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, :all, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :delete_all
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, :price, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, numericality: { greater_than: 0 }
  validates :cooking_time, numericality: { greater_than: 0 }
  validates :description, length: { maximum: 250 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all

    @user = current_user
    # @foods = @user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user = @user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :index, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    food = Food.find(params[:id])
    food.destroy

    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def destroy
  #   @food = Food.find(params[:id])
  #   if @food.destroy
  #     flash.now[:success] = 'Food deleted successfully.'
  #   else
  #     flash.now[:error] = 'Food could not be deleted.'
  #   end
  #   redirect_to foods_path
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)
    redirect_to recipe_path(@recipe.id) if @recipe_food.save
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    redirect_to recipes_path, notice: 'You have successfully added a recipe' if @recipe.save
  end

  def destroy
    recipe = Recipe.find(params[:id])
    redirect_to recipes_path, notice: 'You have successfully deleted a recipe.' if recipe.destroy
  end

  def public
    @recipes = Recipe.includes(recipe_foods: :food).where('public = true')
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shoplist_controller.rb
class ShoplistController < ApplicationController
  def show
    @recipe = Recipe.find(params[:recipe_id])
    @total_items = 0
    @total_price = 0
    @recipe.recipe_foods.includes(:food).each do |item|
      @total_items += item.quantity
      @total_price += item.quantity * item.food.price
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_food.html.erb
<table class="table table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <th scope="row"><%= food.name %></th>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td><%= button_to "Delete", food_path(food.id), method: :delete, class: "btn btn-outline-dark" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/_form.html.erb
<% if food.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
    <ul>
      <% food.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: food) do |form| %>
  <div class='form-control'>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>
  <div class='form-control'>
    <%= form.text_field :measurement_unit, placeholder: 'Measurement Unit' %>
  </div>
  <div class='form-control'>
    <%= form.text_field :price, placeholder: 'Price' %>
  </div>
  <div>
    <%= form.submit "Add Recipe", class: 'button' %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="content">
  <h1 class="page-title">Food List</h1>
  <div class="full-width flex-right"><%= button_to "Add Food", new_food_path, method: :get,  class: 'right' %></div>
  <%= render 'foods/food' %>
</div>

app/views/foods/new.html.erb
<div class="content">
  <h1 class="page-title">New food</h1>
  <%= render "form", food: @food %>
  <div class="link">
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>
  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorGroupReceipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= render partial: "shared/navbar" %>
    <% if notice %>
      <p><%= notice %></p>
    <% end %>
    <div class="content">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<h1 class="page-header">Add ingeridients</h1>
<%= form_with model: @recipe_food, url: recipe_recipe_foods_path  do |f| %>
  <div class="form-control">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="form-control">
    <%= f.label :food, 'Select food' %><br>
    <%= f.select :food_id, @foods.map { |f| [f.name, f.id]}, {}, class: "form-control" %>
  </div>
  <div>
    <%= f.submit "Add Recipe", class: 'button' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="content">
  <h1 class="page-title">Recipes List</h1>
  <div class="full-width flex-right">
    <% if user_signed_in? %>
      <%= button_to "Add Recipe", new_recipe_path, :method => "get" %>
    <% end %>
  </div>

  <% @recipes.each do |recipe| %>
    <%= render partial: "shared/recipe", locals: { recipe: recipe } %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="content">
  <h1 class="page-title">New Recipes</h1>
  <%= form_with model: @recipe, url: recipes_path do |f| %>
    <div class='form-control'>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class='form-control'>
      <%= f.label :preparation_time, 'Preparation time' %><br>
      <%= f.number_field :preparation_time, step: :any %>
    </div>
    <div class='form-control'>
      <%= f.label :cooking_time, 'Cooking time' %><br>
      <%= f.number_field :cooking_time, step: :any %>
    </div>
    <div class='form-control'>
      <%= f.label :public %><br>
      <%= f.check_box :public %>
      <span class="slider round"></span>
    </div>
    <div class='form-control'>
      <%= f.label :description %><br>
      <%= f.text_area :description, size: "70x5" %>
    </div>
    <div>
      <%= f.submit "Add Recipe", class: 'button' %>
    </div>
  <% end %>
</div>

app/views/recipes/public.html.erb
<div class="content">
  <h1 class="page-title">Recipes List</h1>
  <% @recipes.each do |recipe| %>
    <%= render partial: "shared/public_recipe", locals: { recipe: recipe } %>
  <% end %>  
<div>

app/views/recipes/show.html.erb
<div class="content">
  <h1 class="page-title"><%= @recipe.name %></h1>
  <table class="item-header collapse">
    <tr>
      <td>Preparation time: <%= @recipe.preparation_time %> hour</td>
      <td>Public : 
        <label>
          <input type="checkbox" <%= 'checked' || @recipe.public %> >
          <span class="slider round"></span>
        </label>
      </td>
    </tr>
    <tr>
      <td colspan="2">Cooking time: <%= @recipe.cooking_time %> hour</td>
    </tr>
    <tr>
      <td colspan="2"><%= @recipe.description %></td>
    </tr>
  </table>

  <div class="flex-space-between">
    <%= button_to "Genrate shopping list", general_shopping_list_path(recipe_id: @recipe.id), :method => 'get' %>
    <%= button_to "Add ingredients", new_recipe_recipe_food_path(@recipe.id), :method => "get" %>
  </div>

  <table class="table table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Food</th>
        <th>Quantiry</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>

    <% @recipe.recipe_foods.each do |item|%>
      <tr>
        <td><%= item.food.name %></td>
        <td><%= item.quantity %><%= item.food.measurement_unit %></td>
        <td><%= item.food.price * item.quantity %></td>
        <td class="link-list">
          <%= link_to "Modigy" %>
          <%= link_to "Remove" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div><%= link_to 'Recipe App', root_path, class: "navbar-brand" %></div>
  <ul class="navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete } %>
      </li>
      <li class="nav-item">
        <%= link_to 'Foods', foods_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Recipes', recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Recipe',  new_recipe_path, class: "nav-link" %>
      </li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
       <li class="nav-item">
        <%= link_to 'Public Recipes',  public_recipes_path, class: "nav-link" %>
      </li>
  </ul>
</nav

app/views/shared/_public_recipe.html.erb
<div class="flex flex-bordered padding">
  <div>
    <h2 class="list-title"><%= recipe.name %></h2>
    <span>By <%= recipe.user.name %></span>
  </div>
  <ul class="item-list">
    <li>Total food items: <%= recipe.recipe_foods.size %></li>
    <li>Total price: <%= recipe.recipe_foods.inject(0) { |sum, i| sum + (i.food.price * i.quantity) }%>
    </li>
  </ul>
</div>

app/views/shared/_recipe.html.erb
<div class="flex flex-bordered padding">
  <div>
    <h2 class="list-title"><%= recipe.name %></h2>
    <span class="flex-space-between">
      <% if can? :delete, recipe %>
        <%= button_to "DELETE", recipe_path(id: recipe.id), :method => "delete", class: 'margin-right' %>
        <%= button_to "Recipe details", recipe_path(id: recipe.id), :method => "get" %>
      <% end %>
    </span>
  </div>

  <div>
    <p><%= recipe.description %></p>
  </div>

</div>

app/views/shoplist/show.html.erb
<div class="content">
  <h1 class="page-title">Shopping List</h1>
  <div class="flex-space-between">
    <h3>Total Items: <%= @total_items %></h3>
    <h3>Total Price: <%= @total_price %></h3>
  </div>
  <table class="table table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
    <% @recipe.recipe_foods.each do |food|%>
    <tr>
      <td> <%= food.food.name %></td>
      <td><%= food.quantity %> <%= food.food.measurement_unit %></td>
      <td><%= food.food.price * food.quantity %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/index.html.erb
<% if current_user %>
  Hello <%=current_user.name %>
  <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete%>
<% else %>
  <%= link_to "Sign Up!", new_user_registration_path, 'data-turbo-method': :GET%><br/>
  <%= link_to "Sign In", new_user_session_path, 'data-turbo-method': :GET%>
<% end %>